export const orders = [
  {
    id: 1,
    title: 'water Bottle ',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 2,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 3,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 4,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 5,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 6,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 7,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 8,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
  {
    id: 9,
    title: 'Water Can',
    descption: 'Testing description',
    orderDate: new Date(),
    deliveryDate: new Date(),
    price: '₹239.2',
    discount: 10,
    img: 'https://i.pinimg.com/736x/85/45/67/85456788b030f0eb468174fe388d7c9a.jpg',
  },
];

export const productsResponse = [
  {
    id: 1,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 2,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 3,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 4,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 5,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 6,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 7,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 8,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 9,
    name: 'bottle',
    description: 'cold water bottle 20litre',
    price: '500.0',
    images: [],
  },
  {
    id: 10,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 11,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 12,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 13,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 14,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 15,
    name: 'bottle',
    description: 'norwal water bottle 20litre',
    price: '100.0',
    images: [],
  },
  {
    id: 16,
    name: 'Hero 0',
    description: 'bye',
    price: '0.0',
    images: [],
  },
  {
    id: 17,
    name: 'Hero 1',
    description: 'bye',
    price: '1.0',
    images: [],
  },
  {
    id: 18,
    name: 'Hero 2',
    description: 'bye',
    price: '2.0',
    images: [],
  },
  {
    id: 19,
    name: 'Hero 3',
    description: 'bye',
    price: '3.0',
    images: [],
  },
  {
    id: 20,
    name: 'Hero 4',
    description: 'bye',
    price: '4.0',
    images: [],
  },
  {
    id: 21,
    name: 'Hero 5',
    description: 'bye',
    price: '5.0',
    images: [],
  },
  {
    id: 22,
    name: 'Hero 6',
    description: 'bye',
    price: '6.0',
    images: [],
  },
  {
    id: 23,
    name: 'Hero 7',
    description: 'bye',
    price: '7.0',
    images: [],
  },
  {
    id: 24,
    name: 'Hero 8',
    description: 'bye',
    price: '8.0',
    images: [],
  },
  {
    id: 25,
    name: 'Hero 9',
    description: 'bye',
    price: '9.0',
    images: [],
  },
  {
    id: 26,
    name: 'Hero 10',
    description: 'bye',
    price: '10.0',
    images: [],
  },
  {
    id: 27,
    name: 'Hero 11',
    description: 'bye',
    price: '11.0',
    images: [],
  },
  {
    id: 28,
    name: 'Hero 12',
    description: 'bye',
    price: '12.0',
    images: [],
  },
  {
    id: 29,
    name: 'Hero 13',
    description: 'bye',
    price: '13.0',
    images: [],
  },
  {
    id: 30,
    name: 'Hero 14',
    description: 'bye',
    price: '14.0',
    images: [],
  },
  {
    id: 31,
    name: 'Hero 15',
    description: 'bye',
    price: '15.0',
    images: [],
  },
  {
    id: 32,
    name: 'Hero 16',
    description: 'bye',
    price: '16.0',
    images: [],
  },
  {
    id: 33,
    name: 'Hero 17',
    description: 'bye',
    price: '17.0',
    images: [],
  },
  {
    id: 34,
    name: 'Hero 18',
    description: 'bye',
    price: '18.0',
    images: [],
  },
  {
    id: 35,
    name: 'Hero 19',
    description: 'bye',
    price: '19.0',
    images: [],
  },
  {
    id: 36,
    name: 'Hero 20',
    description: 'bye',
    price: '20.0',
    images: [],
  },
  {
    id: 37,
    name: 'Hero 21',
    description: 'bye',
    price: '21.0',
    images: [],
  },
  {
    id: 38,
    name: 'Hero 22',
    description: 'bye',
    price: '22.0',
    images: [],
  },
  {
    id: 39,
    name: 'Hero 23',
    description: 'bye',
    price: '23.0',
    images: [],
  },
  {
    id: 40,
    name: 'Hero 24',
    description: 'bye',
    price: '24.0',
    images: [],
  },
  {
    id: 41,
    name: 'Hero 25',
    description: 'bye',
    price: '25.0',
    images: [],
  },
  {
    id: 42,
    name: 'Hero 26',
    description: 'bye',
    price: '26.0',
    images: [],
  },
  {
    id: 43,
    name: 'Hero 27',
    description: 'bye',
    price: '27.0',
    images: [],
  },
  {
    id: 44,
    name: 'Hero 28',
    description: 'bye',
    price: '28.0',
    images: [],
  },
  {
    id: 45,
    name: 'Hero 29',
    description: 'bye',
    price: '29.0',
    images: [],
  },
];
